# permutation_test_further_checks.py
#
# Study-label permutation test for spatial dissociation between speech and motor
# activation maps within a target ICN mask, using Neurosynth v7 coordinates.
#
# The test restricts to studies that are uniquely tagged as speech or motor,
# builds speech and motor coordinate-density maps inside the mask, and compares
# the observed sum of absolute differences against 10,000 label permutations.
#
# Requires:
#   - Neurosynth v7 coordinates and metadata files
#   - An ICN mask in MNI space (e.g. generated by maskcreation.py)

import os
import numpy as np
import pandas as pd
import nibabel as nib
from nibabel.affines import apply_affine

# =========================================================================
# EDIT ONLY THESE PATHS
# =========================================================================
COORDS_PATH = "path/to/neurosynth_v7/data-neurosynth_version-7_coordinates.tsv.gz"
META_PATH   = "path/to/neurosynth_v7/data-neurosynth_version-7_metadata.tsv.gz"
MASK_PATH   = "path/to/mask/icn17_mask_mni.nii"
RESULTS_DIR = "path/to/output"
# =========================================================================

os.makedirs(RESULTS_DIR, exist_ok=True)

# =========================================================================
# 1. Load mask
# =========================================================================
print("Loading mask...")
mask_img = nib.load(MASK_PATH, mmap=False)
mask_data = np.asanyarray(mask_img.dataobj, dtype=np.float32)
mask_bool = mask_data > 0
affine = mask_img.affine
inv_affine = np.linalg.inv(affine)
print(f"Mask loaded: {mask_data.shape}, voxels inside: {mask_bool.sum()}")

# =========================================================================
# 2. Load Neurosynth data
# =========================================================================
print("Loading Neurosynth...")
coords = pd.read_csv(COORDS_PATH, sep="\t", compression="gzip")
meta   = pd.read_csv(META_PATH, sep="\t", compression="gzip")

text_col = next((c for c in ["title", "description", "terms", "study"] if c in meta.columns), None)
if text_col is None:
    raise ValueError("No text column found in metadata.")
print(f"Using column: {text_col}")

# =========================================================================
# 3. Find study IDs for speech and motor terms
# =========================================================================
def get_study_ids(terms):
    text = meta[text_col].fillna("").astype(str).str.lower()
    mask = np.zeros(len(meta), dtype=bool)
    for t in terms:
        mask |= text.str.contains(t.lower(), na=False)
    return meta.loc[mask, "id"].values

speech_ids = get_study_ids(["speech", "language", "verbal"])
motor_ids  = get_study_ids(["motor", "premotor", "dorsal"])
print(f"Studies: speech {len(speech_ids)}, motor {len(motor_ids)}")

all_ids = np.union1d(speech_ids, motor_ids)
coords_filtered = coords[coords["id"].isin(all_ids)]

speech_only = set(speech_ids) - set(motor_ids)
motor_only  = set(motor_ids) - set(speech_ids)

study_labels = {}
for sid in speech_only:
    study_labels[sid] = 1
for sid in motor_only:
    study_labels[sid] = 0

coords_clean = coords_filtered[coords_filtered["id"].isin(study_labels.keys())]
labels = np.array([study_labels[sid] for sid in coords_clean["id"]])
coords_arr = coords_clean[["x", "y", "z"]].values

n_studies_used = len(np.unique(coords_clean["id"]))
print(f"Coordinates used: {len(coords_clean)} from {n_studies_used} studies "
      f"(speech={len(speech_only)}, motor={len(motor_only)})")

# =========================================================================
# 4. Compute observed map difference
# =========================================================================
def mni_to_voxel_volume(xyz_arr, shape, inv_affine):
    ijk = apply_affine(inv_affine, xyz_arr)
    ijk = np.round(ijk).astype(int)
    valid = (
        (ijk[:, 0] >= 0) & (ijk[:, 0] < shape[0]) &
        (ijk[:, 1] >= 0) & (ijk[:, 1] < shape[1]) &
        (ijk[:, 2] >= 0) & (ijk[:, 2] < shape[2])
    )
    ijk = ijk[valid]
    vol = np.zeros(shape, dtype=np.float32)
    np.add.at(vol, (ijk[:, 0], ijk[:, 1], ijk[:, 2]), 1)
    return vol

speech_xyz = coords_arr[labels == 1]
motor_xyz  = coords_arr[labels == 0]

vol_speech = mni_to_voxel_volume(speech_xyz, mask_data.shape, inv_affine)
vol_motor  = mni_to_voxel_volume(motor_xyz,  mask_data.shape, inv_affine)

s_raw = vol_speech[mask_bool]
m_raw = vol_motor[mask_bool]

obs_diff_sum = np.sum(np.abs(s_raw - m_raw))
print(f"Observed sum of absolute differences: {obs_diff_sum:.2f}")

# =========================================================================
# 5. Permutation test: shuffle study labels
# =========================================================================
def label_permutation_test(xyz, labels, n_perm=10000, seed=42):
    rng = np.random.default_rng(seed)
    n_pts = len(labels)
    diff_perm = np.empty(n_perm)

    print(f"Running {n_perm} label permutations...")
    for i in range(n_perm):
        shuffled_lab = labels[rng.permutation(n_pts)]
        vol1 = mni_to_voxel_volume(xyz[shuffled_lab == 1], mask_data.shape, inv_affine)
        vol2 = mni_to_voxel_volume(xyz[shuffled_lab == 0], mask_data.shape, inv_affine)
        diff_perm[i] = np.sum(np.abs(vol1[mask_bool] - vol2[mask_bool]))
        if (i + 1) % 1000 == 0:
            print(f"  ... {i + 1}/{n_perm}")

    p_val = np.mean(diff_perm >= obs_diff_sum)
    return p_val, diff_perm

p_label, diff_null = label_permutation_test(coords_arr, labels, n_perm=10000)

print("\n--- PERMUTATION TEST RESULTS ---")
print(f"Observed sum of absolute differences = {obs_diff_sum:.1f}")
print(f"P-value (greater) = {p_label:.4f}")
if p_label < 0.05:
    print("Speech and motor maps differ significantly within the mask.")
else:
    print("No significant spatial difference detected between speech and motor maps.")

# =========================================================================
# 6. Save null distribution figure
# =========================================================================
try:
    import matplotlib.pyplot as plt
    plt.figure(figsize=(6, 4))
    plt.hist(diff_null, bins=50, color="gray", alpha=0.7, edgecolor="white")
    plt.axvline(obs_diff_sum, color="red", linestyle="--",
                label=f"Observed = {obs_diff_sum:.1f}")
    plt.xlabel("Sum of absolute differences (permuted labels)")
    plt.ylabel("Frequency")
    plt.title(f"Study-label permutation test\np = {p_label:.4f}")
    plt.legend()
    plt.tight_layout()
    plt.savefig(os.path.join(RESULTS_DIR, "permutation_label_test.png"), dpi=200)
    plt.close()
    print("Null distribution plot saved.")
except ImportError:
    print("matplotlib not installed, skipping plot.")
