# voxelwise_neurosynth_validation.py
#
# Voxelwise anatomical validation of a target ICN mask (e.g. BM17 / ICN17)
# against Neurosynth v7 meta-analytic coordinates.
#
# Steps:
#   1. Load the target ICN mask in MNI space.
#   2. Load Neurosynth v7 coordinates and metadata.
#   3. Select studies tagged with speech/language and motor/premotor terms.
#   4. Build coordinate-density maps for speech and motor studies.
#   5. Normalise (z-score) the maps within the mask.
#   6. Save raw, normalised, and difference volumes.
#   7. Print descriptive stats, top peaks, cluster reports, and Pearson correlation.
#
# Requires:
#   - Neurosynth v7 coordinates and metadata files
#   - A target ICN mask in MNI space (e.g. generated by maskcreation.py)

import os
import numpy as np
import pandas as pd
import nibabel as nib
from nibabel.affines import apply_affine
from scipy.ndimage import label, center_of_mass
from scipy.stats import pearsonr

# =========================================================================
# EDIT ONLY THESE PATHS
# =========================================================================
COORDS_PATH = "path/to/neurosynth_v7/data-neurosynth_version-7_coordinates.tsv.gz"
META_PATH   = "path/to/neurosynth_v7/data-neurosynth_version-7_metadata.tsv.gz"
MASK_PATH   = "path/to/mask/icn17_mask_mni.nii"
OUT_DIR     = "path/to/output"
# =========================================================================

os.makedirs(OUT_DIR, exist_ok=True)

# =========================================================================
# 1. Load ICN mask
# =========================================================================
print("Loading ICN mask ...")
mask_img = nib.load(MASK_PATH, mmap=False)
mask_data = np.asanyarray(mask_img.dataobj, dtype=np.float32)
mask_bool = mask_data > 0
affine = mask_img.affine
inv_affine = np.linalg.inv(affine)
print(f"Mask shape: {mask_data.shape}, voxels inside mask: {mask_bool.sum()}")

# =========================================================================
# 2. Load Neurosynth data
# =========================================================================
print("Loading Neurosynth data ...")
coords = pd.read_csv(COORDS_PATH, sep="\t", compression="gzip")
meta   = pd.read_csv(META_PATH, sep="\t", compression="gzip")
print(f"Coordinates: {len(coords)} rows")
print(f"Metadata columns: {list(meta.columns)}")

# =========================================================================
# 3. Select studies by terms
# =========================================================================
text_col_candidates = ["title", "description", "terms", "study"]
text_col = next((c for c in text_col_candidates if c in meta.columns), None)
if text_col is None:
    raise ValueError(f"No usable text column found. Available: {list(meta.columns)}")
print(f"Using metadata column: '{text_col}'")

def get_study_ids(terms):
    text = meta[text_col].fillna("").astype(str).str.lower()
    mask = np.zeros(len(meta), dtype=bool)
    for t in terms:
        mask |= text.str.contains(t.lower(), na=False)
    id_col = "id" if "id" in meta.columns else meta.index.name
    return meta.loc[mask, id_col].values

speech_terms = ["speech", "language", "verbal"]
motor_terms  = ["motor", "premotor", "dorsal"]

speech_ids = get_study_ids(speech_terms)
motor_ids  = get_study_ids(motor_terms)
print(f"Speech studies found: {len(speech_ids)}, Motor studies found: {len(motor_ids)}")

# =========================================================================
# 4. Filter coordinates
# =========================================================================
speech_coords = coords[coords["id"].isin(speech_ids)]
motor_coords  = coords[coords["id"].isin(motor_ids)]
print(f"Speech coordinates: {len(speech_coords)}, Motor coordinates: {len(motor_coords)}")

if len(speech_coords) == 0 or len(motor_coords) == 0:
    raise ValueError("No coordinates for one or both term sets - check terms or metadata column.")

# =========================================================================
# 5. MNI to voxel accumulation
# =========================================================================
def coords_to_voxel_volume(df, shape, inv_affine):
    xyz = df[["x", "y", "z"]].values.astype(np.float64)
    ijk = apply_affine(inv_affine, xyz)
    ijk = np.round(ijk).astype(int)
    valid = (
        (ijk[:, 0] >= 0) & (ijk[:, 0] < shape[0]) &
        (ijk[:, 1] >= 0) & (ijk[:, 1] < shape[1]) &
        (ijk[:, 2] >= 0) & (ijk[:, 2] < shape[2])
    )
    ijk = ijk[valid]
    vol = np.zeros(shape, dtype=np.float32)
    np.add.at(vol, (ijk[:, 0], ijk[:, 1], ijk[:, 2]), 1)
    return vol

speech_vol = coords_to_voxel_volume(speech_coords, mask_data.shape, inv_affine)
motor_vol  = coords_to_voxel_volume(motor_coords,  mask_data.shape, inv_affine)

raw_speech_path = os.path.join(OUT_DIR, "speech_raw_volume.nii.gz")
raw_motor_path  = os.path.join(OUT_DIR, "motor_raw_volume.nii.gz")
nib.save(nib.Nifti1Image(speech_vol, affine), raw_speech_path)
nib.save(nib.Nifti1Image(motor_vol, affine), raw_motor_path)
print(f"Raw volumes saved: {raw_speech_path}, {raw_motor_path}")

# =========================================================================
# 6. Mask and normalise
# =========================================================================
speech_map = speech_vol[mask_bool]
motor_map  = motor_vol[mask_bool]

def zscore_norm(x):
    x = x.astype(np.float64)
    std = np.std(x)
    if std == 0:
        return np.zeros_like(x)
    return (x - np.mean(x)) / std

speech_map_norm = zscore_norm(speech_map)
motor_map_norm  = zscore_norm(motor_map)

# =========================================================================
# 7. Save masked, normalised maps
# =========================================================================
def save_map(data_1d, mask_3d, affine, fname):
    vol = np.zeros(mask_3d.shape, dtype=np.float32)
    vol[mask_3d > 0] = data_1d
    nib.save(nib.Nifti1Image(vol, affine), fname)
    print(f"Saved: {fname}")

save_map(speech_map_norm, mask_data, affine, os.path.join(OUT_DIR, "speech_map_z.nii.gz"))
save_map(motor_map_norm,  mask_data, affine, os.path.join(OUT_DIR, "motor_map_z.nii.gz"))

# =========================================================================
# 8. Descriptive statistics
# =========================================================================
def map_stats(arr, name):
    print(f"\n--- {name} ---")
    print(f"  Non-zero voxels: {np.count_nonzero(arr)}")
    print(f"  Mean +/- SD: {np.mean(arr):.3f} +/- {np.std(arr):.3f}")
    print(f"  Min: {np.min(arr):.3f}, Max: {np.max(arr):.3f}")
    for pct in [90, 95, 99]:
        print(f"  {pct}th percentile: {np.percentile(arr, pct):.3f}")

map_stats(speech_map_norm, "Speech Map (z-scored)")
map_stats(motor_map_norm,  "Motor Map (z-scored)")

# =========================================================================
# 9. Top peaks
# =========================================================================
def mask_ijk_to_mni(ijk_list, mask_bool, affine):
    mask_ijk = np.argwhere(mask_bool)
    selected_ijk = mask_ijk[ijk_list]
    return apply_affine(affine, selected_ijk)

def top_peaks(data_1d, mask_bool, affine, name, k=5):
    idx = np.argsort(data_1d)[-k:][::-1]
    mni = mask_ijk_to_mni(idx, mask_bool, affine)
    print(f"\nTop {k} peaks in {name}:")
    for i, (coord, val) in enumerate(zip(mni, data_1d[idx])):
        print(f"  {i+1}. MNI: ({coord[0]:.1f}, {coord[1]:.1f}, {coord[2]:.1f})   z = {val:.3f}")

top_peaks(speech_map_norm, mask_bool, affine, "Speech Map", k=5)
top_peaks(motor_map_norm,  mask_bool, affine, "Motor Map", k=5)

# =========================================================================
# 10. Cluster analysis
# =========================================================================
def cluster_report(data_1d, mask_bool, affine, thresh=2.0, name=""):
    vol = np.zeros(mask_bool.shape, dtype=np.int16)
    vol[mask_bool] = (data_1d > thresh).astype(np.int16)
    labeled, n_clusters = label(vol)
    if n_clusters == 0:
        print(f"\nNo clusters found for {name} at z > {thresh}")
        return
    sizes = []
    centres_mni = []
    for i in range(1, n_clusters + 1):
        mask_cluster = labeled == i
        size = np.sum(mask_cluster)
        com_vox = center_of_mass(mask_cluster)
        com_mni = apply_affine(affine, np.array([com_vox]))[0]
        sizes.append(size)
        centres_mni.append(com_mni)
    order = np.argsort(sizes)[::-1]
    print(f"\nCluster report for {name} (z > {thresh}):")
    print(f"  Number of clusters: {n_clusters}")
    for rank, idx in enumerate(order[:10]):
        print(f"  Cluster {rank+1}: {sizes[idx]} voxels, centre MNI: "
              f"({centres_mni[idx][0]:.1f}, {centres_mni[idx][1]:.1f}, {centres_mni[idx][2]:.1f})")

cluster_report(speech_map_norm, mask_bool, affine, thresh=2.0, name="Speech Map")
cluster_report(motor_map_norm,  mask_bool, affine, thresh=2.0, name="Motor Map")

# =========================================================================
# 11. Speech vs motor comparison
# =========================================================================
r, p = pearsonr(speech_map_norm, motor_map_norm)
print(f"\nPearson correlation (Speech vs. Motor): r = {r:.4f}, p = {p:.4e}")

diff = speech_map_norm - motor_map_norm
print("\nDifference map (Speech - Motor):")
print(f"  Mean diff: {np.mean(diff):.3f}")
print(f"  Std diff:  {np.std(diff):.3f}")
print(f"  Max positive (Speech > Motor): {np.max(diff):.3f}")
print(f"  Max negative (Motor > Speech): {np.min(diff):.3f}")

save_map(diff, mask_data, affine, os.path.join(OUT_DIR, "diff_speech_minus_motor_z.nii.gz"))

# =========================================================================
# 12. Optional histogram
# =========================================================================
try:
    import matplotlib.pyplot as plt
    plt.figure(figsize=(8, 4))
    plt.hist(speech_map_norm, bins=100, alpha=0.5, label="Speech", color="blue")
    plt.hist(motor_map_norm,  bins=100, alpha=0.5, label="Motor",  color="red")
    plt.xlabel("z-score")
    plt.ylabel("Voxel count")
    plt.title("Distribution of z-scored coordinate densities inside ICN")
    plt.legend()
    plt.tight_layout()
    plt.savefig(os.path.join(OUT_DIR, "histogram.png"), dpi=150)
    plt.close()
    print(f"\nHistogram saved.")
except ImportError:
    print("\nmatplotlib not installed - skipping histogram.")

# =========================================================================
# 13. Summary
# =========================================================================
print("\n--- RESULTS ---")
print(f"Speech map: mean = {np.mean(speech_map_norm):.4f}, std = {np.std(speech_map_norm):.4f}")
print(f"Motor map:  mean = {np.mean(motor_map_norm):.4f}, std = {np.std(motor_map_norm):.4f}")
print(f"All outputs saved in: {OUT_DIR}")
print("Pipeline complete.")
